# Clave única del proyecto en SonarCloud
sonar.projectKey=kimsonp2908_lab7
# Organización a la que pertenece el proyecto
sonar.organization=kimsonp2908

# Ubicación del código fuente
sonar.sources=src
# Ubicación de las pruebas
sonar.tests=tests
# Inclusión de archivos para el análisis
sonar.python.version=3.11

# Reporte de cobertura generado por pytest-cov
sonar.python.coverage.reportPaths=coverage.xml

# Codificación de los archivos
sonar.sourceEncoding=UTF-8
